name: Trigger Issues
on: issues
jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - name: Echo issue information
        run: |
          echo "Information Issue"
          echo "${{ toJson(github.event) }}"
          
      