name: Trigger Issues
on:
  issues:
    types: [opened, edited, deleted]
jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - name: Echo issue information
        run: |
          echo "Information Issue"
          echo "${{ github.event.issue.number }}. ${{ github.event.issue.title }}"
          echo "${{ github.event.action }}"
          echo "${{ toJson(github.event.changes) }}"
          
      